apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    run: nginx
spec: 
  containers:
    - image: nginx:1.23.3
      imagePullPolicy: IfNotPresent
      name: nginx-container
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: "100m"
          memory: "200Mi"
  restartPolicy: Always